name: CI

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-linux:
    name: build and test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
    env:
      RUST_BACKTRACE: 1
      WGPU_BACKEND: vulkan
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install vulkan libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libvulkan1 mesa-vulkan-drivers vulkan-tools

      - name: Setup rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@ac90e63697ac2784f4ecfe2964e1a285c304003a # v1.14.1
        with:
          rustflags: ""

      - name: Build
        run: cargo build --workspace --all-targets --verbose

      - name: Run tests
        run: cargo test --workspace --verbose
